### ISSUE TITLE
Run from a controller with Artisan::call

### ISSUE THREAD

**Issue by ingnelsoncaraballo** [CrestApps/laravel-code-generator#117]
### Environment:
- Laravel-Code-Generator Version: 2.3.2
- Laravel Version: 5.8.17

### Description:

when you use Artisan::call () to build the resource, it is possible that it generates a file error not found, that is, it does not locate the .json

### Steps/Commands To Reproduce:
For example: Artisan::call("create:scaffold $nombre --translation-for=en,es --with-form-request --with-auth --with-migration --force");

I generated an error

### Content Of The Resource-File:

to correct this it is necessary to use function base_path() in myproject\vendor\crestapps\laravel-code-generator\src\Model\Resource.php on line 683 that contains $fileFullname = Config::getResourceFilePath($filename); 
it should be $fileFullname = base_path(Config::getResourceFilePath($ filename));

**Comment by CrestApps** [comment]
The problem with your approach is that the environment path is different from HTTP request than a console call. 
When the `file_exists()` function is called from an HTTP request, it uses the public path at the base for the files. However, when `file_exists()` is called from the console request, the root of the project is used which works as expected.

The easiest way to fix this issue is to change the resource path temporary like so before calling `Artisan::call()`

```
Config::set('laravel-code-generator.resource_file_path', '../resources/laravel-code-generator/sources');
Artisan::call("create:scaffold $nombre --translation-for=en,es --with-form-request --with-auth --with-migration --force");
```
