### ISSUE TITLE
Install version 2.4.1 in Laravel Framework 6.5.0 is passed but Unable to locate publishable resources and missing configuration files code_generator.php and  code_generator_custom.php

### ISSUE THREAD

**Issue by mauphung** [CrestApps/laravel-code-generator#133]
Install version 2.4.1 in Laravel Framework 6.5.0 is passed.
C:\www\test>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing crestapps/laravel-code-generator (v2.4.1): Downloading (100%)

But Unable to locate publishable resources and missing configuration files code_generator.php and  code_generator_custom.php
C:\www\test>php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default
Unable to locate publishable resources.
Publishing complete.

**Comment by CrestApps** [comment]
Since the documentation page is not uptodate, please read the [change log](https://github.com/CrestApps/laravel-code-generator/blob/master/CHANGELOG.md#v230) so you know what changed.

Below are couple of important bullets that you may want to follow. Then if you want to override the default settings, run ` php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=config`  that will create a new file called `laravel-code-generator.php` where you'll need to store the custom configuration.

The user is no longer required to publish the default templates. This is much better step to prevent upgrade braking when the template are updated during a patch release. The user should publish templates only if he/she want to modify it and rename it. **IMPORTANT** Delete existing default and default-collective templates from the folders from the default publish path of your project.

**IMPORTANT**: delete the the codegenerator.php file from your config folder, then rename the codegenerator_custom.php file to laravel-code-generator.php. Alternatively, you can delete both codegenerator.php and codegenerator_custom.php
