### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jchimene** [CrestApps/laravel-code-generator#136]
### Environment:
- Laravel-Code-Generator Version: v2.4.2
- Laravel Version: 6.x

### Description:
Unable to installation

### Steps/Commands To Reproduce:
composer require crestapps/laravel-code-generator --dev

Yields the following

[error.log](https://github.com/CrestApps/laravel-code-generator/files/3825984/error.log)

### Content Of The Resource-File:
N/A

**Comment by 1kakarot** [comment]
I get the same error.
I had to install 2.4.1 with
composer require crestapps/laravel-code-generator:2.4.1 --dev

**Comment by CrestApps** [comment]
Can you please try removing the existing package and reinstalling?

**Comment by geller007** [comment]
The same code for “vendor/crestapps/laravel-code-generator/src\Commands\Bases\ControllerCommandBase.php” and “vendor/crestapps/laravel-code-generator/src\Commands\Framework\CreateModelCommand.php”.

**Comment by 1kakarot** [comment]
@CrestApps 
The same think happens
`Package operations: 1 install, 0 updates, 0 removals
  - Installing crestapps/laravel-code-generator (v2.4.2): Loading from cache
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "CrestApps\CodeGenerator\Commands\Bases\ControllerCommandBase" was found in both "/var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Bases/ControllerCommandBase.php" and "/var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Framework/CreateModelCommand.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Cannot declare class CrestApps\CodeGenerator\Commands\Bases\ControllerCommandBase, because the name is already in use in /var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Framework/CreateModelCommand.php on line 16

   Symfony\Component\Debug\Exception\FatalErrorException  : Cannot declare class CrestApps\CodeGenerator\Commands\Bases\ControllerCommandBase, because the name is already in use

  at /var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Framework/CreateModelCommand.php:16
    12| use CrestApps\CodeGenerator\Support\ViewLabelsGenerator;
    13| use CrestApps\CodeGenerator\Traits\LanguageTrait;
    14| use CrestApps\CodeGenerator\Traits\ModelTrait;
    15| 
  > 16| abstract class ControllerCommandBase extends ControllerRequestCommandBase
    17| {
    18|     use ModelTrait, LanguageTrait;
    19| 
    20|     /**


   Whoops\Exception\ErrorException  : Cannot declare class CrestApps\CodeGenerator\Commands\Bases\ControllerCommandBase, because the name is already in use

  at /var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Framework/CreateModelCommand.php:16
    12| use CrestApps\CodeGenerator\Support\ViewLabelsGenerator;
    13| use CrestApps\CodeGenerator\Traits\LanguageTrait;
    14| use CrestApps\CodeGenerator\Traits\ModelTrait;
    15| 
  > 16| abstract class ControllerCommandBase extends ControllerRequestCommandBase
    17| {
    18|     use ModelTrait, LanguageTrait;
    19| 
    20|     /**

  Exception trace:

  1   Whoops\Run::handleError("Cannot declare class CrestApps\CodeGenerator\Commands\Bases\ControllerCommandBase, because the name is already in use", "/var/www/blog/vendor/crestapps/laravel-code-generator/src/Commands/Framework/CreateModelCommand.php")
      /var/www/blog/vendor/filp/whoops/src/Whoops/Run.php:433

  2   Whoops\Run::handleShutdown()
      [internal]:0
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

Installation failed, reverting ./composer.json to its original content.
`

**Comment by jchimene** [comment]
thx. I'll try ASAP

**Comment by CrestApps** [comment]
This should be fixed by using v2.4.4

**Comment by 1kakarot** [comment]
Great!
