### ISSUE TITLE
No "hasMany" relationship methods generated

### ISSUE THREAD

**Issue by mohaghegh** [CrestApps/laravel-code-generator#23]
Hi
Regarding [issue #3](https://github.com/CrestApps/laravel-code-generator/issues/3) , "hasMany" part of the ralationships are not generated when generating resources from existing database.
In my project there are two tables: countries and provinces.
Running this command:
`php artisan create:resources Province --table-name hmk_provinces --table-exists --translation-for=en,fa --force`
generates a nice model file containing country method:
`public function country()
{
    return $this->belongsTo('App\Models\Country','country_id');
}`
but the reverse method (e.g. provinces) is not generated in Country model file when running this command:
`php artisan create:resources Province --table-name hmk_provinces --table-exists --translation-for=en,fa --force`

Am I going wrong way?
Thanks a lot

**Comment by CrestApps** [comment]
Can you please post your database scheme here?

Show Create Table hmk_provinces;
Show Create Table hmk_countries;

**Comment by mohaghegh** [comment]
Here's the schema.

"hmk_provinces" :
```
CREATE TABLE `hmk_provinces` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(250) DEFAULT NULL,
 `country_id` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `idx_provinces` (`country_id`),
 CONSTRAINT `fk_provinces` FOREIGN KEY (`country_id`) REFERENCES `hmk_countries` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

"hmk_countries" :
```
CREATE TABLE `hmk_countries` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(250) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by CrestApps** [comment]
Thank you for sharing the schema with us.

Unfortunately that is a current limitation in the code generator. Currently it automatically handles the `belongsTo` relation between the objects.

However, this is something we are looking to implement in future release (possible in the next minor release.)

For now, you'll have to manually add the `hasMany` relation on the Country model.

Thank you for your feedback and please keep them coming :)

**Comment by mohaghegh** [comment]
Good.
I'm sure it will be implemented as perfect as other parts of this handy code-generator :)

Watching for upcoming releases, with feedbacks and star ;)

**Comment by CrestApps** [comment]
@mohaghegh good news! This feature have been implemented in a separate branch (i.e v2.2dev) It is not ready to be released yet, but feel free to try it out https://github.com/CrestApps/laravel-code-generator/tree/v2.2dev

There are couple things that are worth mention
1. The `--fields-file` option in all command have been changed to `--resource-file` since that file is no longer just a fields-file.
2. This branch completely drop support for fields from raw string. We relay heavy on the JSON-based `resource-file`. The `resource-file` allows you to define any relations, indexes and fields all at one.
3. The following command have been renamed
 - The command `create:fields-file` has been renamed to `resource-file:from-database`
 - The command `fields-file:create` has been renamed to `resource-file:create`
 - The command `fields-file:delete` has been renamed to `resource-file:delete`
 - The command `fields-file:append` has been renamed to `resource-file:append`
 - The command `fields-file:reduce` has been renamed to `resource-file:reduce`

Please let me know if you use it and if you encounter any unexpected bugs!

Thank you

**Comment by CrestApps** [comment]
I am closing this ticket for now since this feature will be part of the new coming up release version 2.2.0

For more info about the new release, http://crestapps.dev/laravel-code-generator/docs/2.2
