### ISSUE TITLE
Wrong html-type for json fields. 

### ISSUE THREAD

**Issue by Mist3** [CrestApps/laravel-code-generator#33]
### Environment:
- Laravel-Code-Generator Version: dev
- Laravel Version: 5.5.16

### Description:
I have migration with field declared as JSON (sent_json_msg). 
The Code generator throws error "The field sent_json_msg has no options!". 

### Steps/Commands To Reproduce:
Create migration with field: 
            $table->json('sent_json_msg')->nullable();
Run artisan migrate.
Run artisan create:resources ModelName --table-exists

### Content Of The Resource-File:
{
            "name": "sent_json_msg",
            "labels": "Sent Json Msg",
            "html-type": "checkbox",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "nullable|array",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "json",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },

**Comment by CrestApps** [comment]
Thank you for your interest in this package and your desire to help improving it.

If you look at the default config file (i.e `config/codegenerator.php`) file, we set the ``html-type` to `checkbox` by default in the `eloquent_type_to_html_type` key https://github.com/CrestApps/laravel-code-generator/blob/master/config/codegenerator.php#L641

So the code generator did exactly that for you. However, to be able to construct checkboxes, you need to list at least one option in the `options` properties to construct the checkboxes.

The Code-Generator, it telling you "I can't construct the `checkboxes` unless you give me at least one option".

Since the HTML values are not stored in the database somewhere, you'll need to manually provide the options. 

Try changing the content of the resource file to the following. This code should show you three checkboxes labeled "One","Two" and "Three"

```
{
"name": "sent_json_msg",
"labels": "Sent Json Msg",
"html-type": "checkbox",
"css-class": "",
"options": {
    "one": "One",
    "two": "Two",
    "three": "Three"
},
"html-value": null,
"validation": "nullable|array",
"is-on-index": false,
"is-on-show": true,
"is-on-form": true,
"data-type": "json",
"data-type-params": [],
"data-value": null,
"is-index": false,
"is-unique": false,
"is-primary": false,
"comment": null,
"is-nullable": true,
"is-header": false,
"is-unsigned": false,
"is-auto-increment": false,
"is-inline-options": false,
"is-date": false,
"date-format": "",
"cast-as": "",
"placeholder": {},
"delimiter": "; ",
"range": [],
"foreign-relation": null,
"foreign-constraint": null,
"on-store": null,
"on-update": null
},
```
