### ISSUE TITLE
Incorrect use statement generated in controller if models_path is blank

### ISSUE THREAD

**Issue by tkerns** [CrestApps/laravel-code-generator#60]
### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 6.6

### Description:
I am trying to create a project with the models in the app root (as opposed to a Models directory), as Laravel 5.6 seems to do by default.
I am setting the  models path to an empty string in the config file
`'models_path' => '',`

When you generate a controller , and model_path is blank in config, there is an extra \ between App and model name in controller use statement.
`use App\\ModelName`

### Steps/Commands To Reproduce:
generate a resource file 
create:resources ModelName

look in created controller, and the use statement for the model has extra backslash.

**Comment by CrestApps** [comment]
This issue is now fixed with [v2.2.10](https://github.com/CrestApps/laravel-code-generator/releases/tag/v2.2.10)

I recommend you group your model classed into a models folder regardless of where Laravel choose to to put the `User` model by default. + You can always change where the `User` model is located.

**Comment by tkerns** [comment]
Thank you!  This generator is awesome, and has been a great time saver for me.  Keep up the great work!
