### ISSUE TITLE
template bootstrap 4

### ISSUE THREAD

**Issue by nicolaszanghi** [CrestApps/laravel-code-generator#61]
Hello,

Did someone created a template for Bootstrap v4 ?

**Comment by CrestApps** [comment]
I am not aware of anyone that did that. It should be a straight forward process. 

If you would like to contribute into this package, feel free to fork branch v2.3 (https://github.com/CrestApps/laravel-code-generator/tree/v2.3) and create 2 new templates that support bootstrap 4.
Here is the instruction on how to create a custom template (https://www.crestapps.com/laravel-code-generator/docs/2.2#how-to-create-custom-template).

**Comment by Ybansan** [comment]
Hi,
I created a template for Bootstrap 4. I would like to contribute, but I do not have write access to the repository, in order to branch.

**Comment by CrestApps** [comment]
Ybansab that is great! What issue are you running into while trying to fork the project? Please note tha Instead of foking the project, I would just create a new project in your own GitHub account and maintain the new template there. If for some reason you don’t want to create that project on your own account, I can create a new project for bootstrap4 project and you can commit to the new project. But I think you should own that project on your own account

**Comment by Ybansan** [comment]
As you want. In fact I am new to GitHub. I will try according to your recommendation.

**Comment by Ybansan** [comment]
https://github.com/Ybansan/crestapps-bootstrap4-templates
It was hard to do for me, a newbie with github, but I learned a lot.
Thank you Mike for your advices and your job.

**Comment by CrestApps** [comment]
Great work! Glad I can help. I suggest you do the following

1. Make 2 templates, one to support Laravel-collective and another one for the standard code. Name them something like bootstrap4 and collective-bootstrap4 not all users like to use Laravel-collective to generate code.

2. Add a service provider in your package so the user can run the ‘php artisan vendor:publish ... ‘ command to publish the template instead of having to do that manually. Here is an example of a service provider https://github.com/CrestApps/laravel-code-generator/blob/master/src/CodeGeneratorServiceProvider.php

3. In the installation instruction, you should ask the user to add the configuration into the ‘codegenerator_custom.php’ file

**Comment by diorz38** [comment]
i think, ist not too difficult to do that, i can manage build some of custom stub file (template) with free admin template (i use extreme Admin Lite from WrapPixel), the problem is, i dont know how to put name of main layout dynamicaly on @extend() line, so i just hard coded it:blush:

[index.blade.stub.zip](https://github.com/CrestApps/laravel-code-generator/files/2299660/index.blade.stub.zip)

**Comment by Ybansan** [comment]
Hi Mike,

I put in practice your advices 1 and 2:

- Template names now are `bootstrap4` and `collective-bootstrap4`.
- Templates are published with `php artisan vendor:publish...`.

I did not made a `v2.3`. I prefer to wait and apply changes over templates from a stable version.
