### ISSUE TITLE
Making better CrestApp. Bigger

### ISSUE THREAD

**Issue by gettedgui** [CrestApps/laravel-code-generator#73]
### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 5.5

### Description:
I really want to add many good things to your package (CrestApp), but I need to know exactly the meaning of some code. When resource.json is generated: what does mean range? what does mean protection part? what is the diference between foreign-constraint and foreign-relation and how that diference influence the diferent resource to create?
Another thing, how can I understand the structure of a template.

My goals are:
1.- include enum in data type to combine with select, check b. or radio b.
2.- generate the index table with datatable
3.- include roles and permission
4.- include some plug-ins for the kind of data that need picker (time picker, color picker, date range picker, etc) in forms
5.- create a group of layout to select, or select from other free template, like AdminLTE
6.- include a package to make menus
7.- Add logins with social networks
8.- Add cells in tables with formulas (May be creating views in the data base and use them like model with migrations)
9. Add data (with two cells) for Google maps location

Wow! I have some many ideas to make CrestApp greater just using php artisan comands

and many other things how make your package one of the best pakage por Laravel.
Even, I want to translate to Spanish the manual, and make complete videos on youtube (in English and Spanish), but I need all information about how work templates files, and the meaning with each detail (and an example) of the json file to generate de resource.

Another thing. why i must generate the resource and migration on MySQL and then make migration again on Postgresql if I want to use Postgresql from the begining?

May I take information about how to do that.

Thank for your patience and your time, but CrestApp is awesome and can be the best tool for Laravel.

I need the info ASAP because more than three project depend on it.

Help me please

![captura de 2018-08-06 18 57 02](https://user-images.githubusercontent.com/38214698/43745003-a3da54e0-99aa-11e8-8fd3-67f24d4a6e99.png)

**Comment by CrestApps** [comment]
First of all, I would suggest that you dig deep into the code before making any change. The code isn't hard to read but you'll need to understand what is going on so you can add/modify the right places. Also, I suggest starting a new branch on github with your change. Also, make sure you branch off the v2.3 branch NOT the master branch https://github.com/CrestApps/laravel-code-generator/tree/v2.3 as the v2.3 has all the new futures like API and API documentation generators.. Plus the code is a bit cleaner.

To get started I would suggest you look at the CreateControllerCommand class https://github.com/CrestApps/laravel-code-generator/blob/v2.3/src/Commands/Framework/CreateControllerCommand.php this will give you an idea of the code structure. Once you are confertable with the code, I would suggest you look at the HtmlGenerators https://github.com/CrestApps/laravel-code-generator/tree/v2.3/src/HtmlGenerators this way you understand how to templates are converted into ready code.


**what does mean range?** range is used to set the range for the `selectRange` html type. If you want a menu between 1 and 50 then you would pass `1:50`. It has been a while since I looked at the code so forgive me if I am mistaken.

*What does mean protection part?** This is for your own protected. If you set any of the flags to true, then even if you pass `--force` option to the commands, the corresponding file will not get override. It is a way to lock your work to protect you from you :). This feature comes in handy when you need to make manual code change to the generated files and you want to ensure that no once by mistake try to regenerated the code using `--force` command and wipe out your code. For example, if you set `"is-controller-protected": true` and someone try to generate the controller with the `--force` option, the code-generator will give you a warning and will not allow you to override the file unless you manually set back to false (i.e `"is-controller-protected": false` )


**What is the difference between foreign-constraint and foreign-relation and how that difference influence the different resource to create?** The foreign-constraint is a constraint that is applied at the database. The foreign-relation allows you to create eloquent-relation or navigation properties. You can also think about it like this every foreign-constraint will/should always have a foreign-relation to represent it where as not every foreign-relation required a constraint on the database, foreign-constraints on the database are used to keep your data clean but add overhead to your database. For more info read the following links https://www.crestapps.com/laravel-code-generator/docs/2.2#foreign-relations   https://laravel.com/docs/5.6/eloquent-relationships https://laravel.com/docs/5.6/migrations#foreign-key-constraints


**Another thing, how can I understand the structure of a template.** Not sure what you really looking for. But if you want to understand how the templates are generated, I would start looking at the html-generator classes https://github.com/CrestApps/laravel-code-generator/tree/v2.3/src/HtmlGenerators

My goals are:
**1.- include enum in data type to combine with select, check b. or radio b.** Not sure what your trying to do or what problem you're trying to solve
**2.- generate the index table with data-table.** Cool, few people asked for this feature. However, I would suggest making a datatable-template and make it a separate project. I would not want to add new templates as part of the core package. I would recommend making the code-generator able to fulfill the requirement to for the new template but put the template itself into a separate project.
**3.- include roles and permission** I would like to know more about this. The code generator is for generating code not writing solutions. Meaning I don't want to tightly couple this project with external project as I don't want to force people be forced to use only one implementation/package. I would suggest tweaking the templates "by adding more variables" to allow someone that has a role/permission package to generate code that fits their need. I hope this makes sense. And again, you would create a template that support a your own role/permission package.
**4.- include some plug-ins for the kind of data that need picker (time picker, color picker, date range picker, etc) in forms.** Unless your talking about the new html-5 element, you should be able to do this today. I would use the `css-class` to add css-classes to the fields like `datetime-picker` and then write javascript code that would create a datetime-picker using this class. Read this from the code https://www.crestapps.com/laravel-code-generator/docs/2.2#model-clean-fields
**5.- create a group of layout to select, or select from other free template, like AdminLTE** Like I mentioned in bullet 3, I would create layout/templates in an external project to do this. just make sure the code-generator is able to fully replace all your required variables.
**6.- include a package to make menus** Agreed. This is something on the to do this. Share with me your thoughts before start writing the code if you don't mind please.
**7.- Add logins with social networks** again this is the same thing as for bullet 3 above. I would like to know more. This package already have support for laravel-passport. Not sure where you heading with this but again I would not want tightly couple this project with an external project. https://laravel.com/docs/5.6/passport
**8.- Add cells in tables with formulas (May be creating views in the data base and use them like model with migrations)** Virtual-fields is something on my list as well. Please share with me your thought on how your thinking on approaching this.
**9. Add data (with two cells) for Google maps location** no idea what is this.

**Even, I want to translate to Spanish the manual, and make complete videos on youtube (in English and Spanish), but I need all information about how work templates files, and the meaning with each detail (and an example) of the json file to generate de resource.** This would be really good a very helpful. If you want to know more I suggest you dig in the code while I can answer specific questions. In most cases the properties in the json file are self-explanatory, left me know if you have a specific question. 

Another thing. why i must generate the resource and migration on MySQL and then make migration again on Postgresql if I want to use Postgresql from the beginning? Yes, I would like to make the generator include support every driver Laravel support. I just have not found time to write implementation for other drivers. But this should be a fairly easy task to take on, Here is the MySQL implementation https://github.com/CrestApps/laravel-code-generator/blob/v2.3/src/DatabaseParsers/MysqlParser.php I would say just following that same logic. You'll need to re-write the MySQL queries into Postgresql queries and the rest of the code would stay the same for the most part. Make sure that the class is called `PostgresqlParser` and is located next to `MySqlParser.php` file then go to the following file and change line 48 from `protected $drivers = ['mysql'];` to `protected $drivers = ['mysql','postgresql'];`

https://github.com/CrestApps/laravel-code-generator/blob/0c3787212a196bf19072cd95036336a5d5f79ea3/src/Commands/ResourceFileFromDatabaseCommand.php#L48

I hope this helps. Let me know if you have additional questions

**Comment by gettedgui** [comment]
Thanks you very much. I'll be in contact with you again for sure. For now,
I need to work on a projects and i will use your ideas to do that. In the
mean time, I going to start translate your manual (crestapp.com) Spanish
version, If I have any question about the text, I will contact you.

I very pleased about your speed answering and the details you do. You are
very serius people.



Atentamente,

Gustavo Enrique Ettedgui Ponce

2018-08-06 22:36 GMT-04:00 CrestApps <notifications@github.com>:

**Comment by CrestApps** [comment]
I am closing this issue for now. Feel free to contact me with any more questions
